[platformio]
src_dir = .

[env:SimpleSerialExample]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_deps =
    paulstoffregen/Time @ ^1.6.1
lib_extra_dirs = ../..

monitor_speed = 115200