[platformio]
src_dir = .

[env:TimerExample]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_deps =
    paulstoffregen/Time @ ^1.6.1
lib_extra_dirs = ../..
build_flags = -D ELOG_TIMER_ENABLE

monitor_speed = 115200