[platformio]
src_dir = .

[env:SdExample]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_deps =
    adafruit/SdFat - Adafruit Fork @ ^2.3.52
    paulstoffregen/Time @ ^1.6.1
lib_extra_dirs = ../..
build_flags =
    -D ELOG_SD_ENABLE
    -D DISABLE_FS_H_WARNING

monitor_speed = 115200